name: 'Copy File to Another Repository'
inputs: # Copied from dmnemec/copy_file_to_another_repo_action
  source_file:
    description: 'Source file from the origin directory'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_folder:
    description: 'Directory to push the file to'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_branch:
    description: 'branch to push file to, defaults to main'
    required: false
    default: main
  destination_branch_create:
    description: 'Destination branch to create for this commit'
    required: false
  commit_message:
    description: 'A custom message for the commit'
    required: false
  rename:
    description: 'Rename the destination file'
    required: false
  use_rsync:
    description: 'Copy files/directories using rsync instead of cp. Experimental feature, please know your use case'
    required: false
  git_server:
    description: 'Git server host, default github.com'
    required: false
    default: github.com
runs:
  using: "composite"
  steps:
  - id: generate-temp-dir
    run: export CLONE_DIR=$(mktemp -d)
    shell: bash

  - id: configure-git
    run: |
      echo "Cloning destination git repository"
      git config --global user.email "${{ inputs.user_email }}"
      git config --global user.name "${{ inputs.user_name }}"
  - id: clone-repo
    run: git clone --single-branch --branch ${{ inputs.destination_branch }} "https://x-access-token:$API_TOKEN_GITHUB@${{ inputs.git_server }}${{ inputs.destination_repo }}.git" "$CLONE_DIR"
    
  - id: rename
    if: ${{ input.rename != "" }}
    run: |
      echo "Setting new filename: ${{ input.rename }}"
      export DEST_COPY="$CLONE_DIR/${{ input.destination_folder }}/${{ input.rename }}"
    shell: bash
  - id: rename
    if: ${{ input.rename == "" }}
    run: export DEST_COPY="$CLONE_DIR/${{ input.destination_folder }}"
    shell: bash

  - id: copy-items
    if: ${{ input.use_rsync == "" }}
    run: cp -R "${{ input.source_file }}" "$DEST_COPY"
  - id: copy-items-rsync
    if: ${{ input.use_rsync != "" }}
    run: rsync -avrh "${{ input.source_file }}" "$DEST_COPY"

  - id: cd
    run: cd "$CLONE_DIR"
    shell: bash

  - id: create-destination-branch
    if: ${{ input.destination_branch_create != "" }}
    run: |
      echo "Creating new branch: ${{ input.destination_branch_create }}"
      git checkout -b "${{ input.destination_branch_create }}"
      export OUTPUT_BRANCH="${{ input.destination_branch_create }}"
  - id: set-output-branch
    run: export OUTPUT_BRANCH="${{ input.destination_branch }}"
    shell: bash

  - id: set-commit-message
    if: ${{ input.commit_message == "" }}
    run: export COMMIT_MESSAGE="Update from https://${{ input.git_server }}/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
  - id: set-commit-message
    if: ${{ input.commit_message != "" }}
    run: export COMMIT_MESSAGE="${{ input.commit_message }}"

  - id: commit-and-push
    run: |
      echo "Adding git commit"
      git add .
      git commit --message "$COMMIT_MESSAGE"
      echo "Pushing git commit"
      git push -u origin HEAD:"$OUTPUT_BRANCH"


  - id: cd-back
    run: cd -
    shell: bash
